name: sme_app_aluno
description: SME Aplicativo do Aluno

version: 1.4.13+13

environment:
  sdk: ^3.10.0

scripts:
  pget: flutter pub get
  brunner: flutter pub run build_runner build
  fclean: flutter clean
  icons: flutter pub run flutter_launcher_icons:main

dependencies:
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^1.1.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.6.0
  connectivity_plus: ^7.0.0
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  brasil_fields: ^1.14.1
  cpf_cnpj_validator: ^2.0.0
  json_serializable: ^6.11.3
  json_annotation: ^4.8.1
  firebase_messaging: ^16.0.4
  firebase_analytics: ^12.0.4
  intl: ^0.20.2
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html_core: ^0.17.0
  
  device_info_plus: ^12.3.0
  url_launcher: ^6.1.14
  string_validator: ^1.0.2
  email_validator: ^3.0.0
  sentry: ^9.8.0
  awesome_dialog: ^3.1.0
  sqflite: ^2.3.0
  path: ^1.8.3 
  local_auth: ^3.0.0 
  background_fetch: ^1.5.0
  hexcolor: ^3.0.1
  get_it: ^9.2.0
  shared_preferences: ^2.2.2
  extended_masked_text: ^3.0.0
  dio: ^5.3.3
  grouped_list: ^6.0.0
  flutter_easyloading: ^3.0.5
  getwidget: ^7.0.0
  get_ip_address: ^0.0.6
  firebase_core: ^4.2.1
  html: ^0.15.4
  package_info_plus: ^9.0.0
  win32: ^5.3.0
  dartz: ^0.10.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.4 
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4 
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.20
  analyzer: ^8.4.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - config/app_config.json

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
