name: sme_app_aluno
description: SME Aplicativo do Aluno

version: 1.3.5+6

environment:
  sdk: ">=2.1.0 <3.0.0"

scripts:
  pget: flutter pub get
  brunner: flutter pub run build_runner build
  fclean: flutter clean

dependencies:
  shimmer: ^1.1.2
  percent_indicator: ^2.1.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.3.2+2
  http: ^0.12.2
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.8.1
  package_info: ^0.4.0+16
  connectivity: ^0.4.8+6
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0
  brasil_fields: ^0.2.0
  cpf_cnpj_validator: ^1.0.5
  json_serializable: ^3.3.0
  json_annotation: ^3.0.1
  getflutter: ^1.0.11
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.1
  firebase_analytics: ^6.1.0
  intl: ^0.16.1
  flutter_html: ^0.11.1
  device_info: ^0.4.2+2
  url_launcher: ^5.4.10
  string_validator: ^0.1.4
  email_validator: ^1.0.4
  sentry: ">=3.0.0 <4.0.0"
  mockito: ^4.1.1
  awesome_dialog: ^1.1.3
  sqflite: ^1.3.2+1
  path: 
  local_auth: ^0.6.2+3
  get_ip: ^0.4.0
  background_fetch: '^0.5.1'
  hexcolor: ^1.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
